### ISSUE TITLE
Issue running mlpm (install) with Node v5

### ISSUE THREAD

**Issue by grtjn** [joemfb/mlpm#12]
Reported from field. It looks like mlpm includes a version of request dependency that chokes for some reason. I can dig up more details if needed..

**Comment by joemfb** [comment]
More details would help if you can. I don't think request has changed that drastically. (Some other dependencies are pretty far behind, but I'll need to test them on different node versions).

**Comment by joemfb** [comment]
mlpm v0.6.1 is now out, test on node 8.
