### ISSUE TITLE
Republish package failed

### ISSUE THREAD

**Issue by grtjn** [joemfb/mlpm#3]
I published a new package (initial version), than thought I forgot to update something, so I unpublished the version (I had to use -f by the way), then tried to republish. The latter failed with:

```
[Error: HTTP 400: Bad Request, unpublished version exists (UNPUBLISHED-EXISTS): ml-open-calais 1.0.0]
```

Shouldn't unpublish just get rid of package/version? How else to republish a particular version?

**Comment by joemfb** [comment]
You can't republish, or push any changes, to an already published version. This restriction also exists in other package managers, and it protects users by making a specific package version immutable. Just increment the version number by running `mlpm version patch` and then re-publish.
