### ISSUE TITLE
deploy command does not deploy modules on server

### ISSUE THREAD

**Issue by peetkes** [joemfb/mlpm#9]
I just tried deploying modules with mlpm deploy but besides the message deploying packages... nothing happens.
Same for the roxy method.
Did something change?

Steps to reproduce:
mkdir test
cd test
mlpm init
mlpm install taskbot --save
mlpm deploy -u [user] -p [pwd] -H [host] -P [port]
deploying packages ...

but nothing gets deployed in teh modules db connected to [port]

**Comment by grtjn** [comment]
Also fails for other packages, like ml-unique, according to @peetkes..

**Comment by joemfb** [comment]
Does `[port]` point at a REST API instance?

**Comment by joemfb** [comment]
I've reproduced the bug; looks like I broke something in the last release ... Investigating now.

**Comment by joemfb** [comment]
This was a bug that always present, but hidden by the bug in #8. I was failing to invoke a callback in some cases where I couldn't detect any XQuery metadata. I've fixed this, and added tests for these types of scenarios.

I'll cut a new patch release.

**Comment by joemfb** [comment]
I've released `0.5.1` with this fix. Thanks for the report!

**Comment by grtjn** [comment]
Thnx for fixing! :-)

**Comment by peetkes** [comment]
Thanks for the fix!

Regards,

Peter
